"""ajout statut ANNULEE

Revision ID: a821aa3693f5
Revises: cb4bd8e1bd49
Create Date: 2026-08-13 00:11:26.422510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a821aa3693f5'
down_revision: Union[str, Sequence[str], None] = 'cb4bd8e1bd49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
