"""creation des tables

Revision ID: cb4bd8e1bd49
Revises: 
Create Date: 2026-07-17 22:19:25.120772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4bd8e1bd49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=8), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRATEUR', 'LIVREUR', 'CLIENT', name='roleenum'), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('livreurs',
    sa.Column('id_livreur', sa.String(), nullable=False),
    sa.Column('type_vehicule', sa.Enum('MOTO', 'VOITURE', name='vehiculeenum'), nullable=False),
    sa.Column('immatriculation', sa.String(length=20), nullable=False),
    sa.Column('etat_activite', sa.Enum('HORS_LIGNE', 'DISPONIBLE', 'EN_COURSE', name='etatactiviteenum'), nullable=False),
    sa.Column('est_actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_livreur'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id_livreur'),
    sa.UniqueConstraint('immatriculation')
    )
    op.create_table('commandes',
    sa.Column('id_commande', sa.String(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('adresse_ramassage', sa.Text(), nullable=False),
    sa.Column('adresse_livraison', sa.Text(), nullable=False),
    sa.Column('nom_destinataire', sa.String(length=200), nullable=False),
    sa.Column('telephone_destinataire', sa.String(length=8), nullable=False),
    sa.Column('telephone_demandeur', sa.String(length=8), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('montant_a_percevoir', sa.Float(), nullable=False),
    sa.Column('statut_commande', sa.Enum('EN_ATTENTE', 'ASSIGNEE', 'EN_COURS_DE_COLLECTE', 'EN_COURS_DE_LIVRAISON', 'LIVREE', name='statutcommandeenum'), nullable=False),
    sa.Column('id_livreur', sa.String(), nullable=True),
    sa.Column('id_client', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['id_livreur'], ['livreurs.id_livreur'], ),
    sa.PrimaryKeyConstraint('id_commande'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('notifications',
    sa.Column('id_notification', sa.String(), nullable=False),
    sa.Column('id_commande', sa.String(), nullable=False),
    sa.Column('telephone_destinataire', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('statut_envoi', sa.Enum('EN_ATTENTE', 'ENVOYE', 'ECHEC', name='statutenvoienum'), nullable=False),
    sa.Column('declencheur', sa.Enum('ASSIGNEE', 'EN_COURS_DE_LIVRAISON', name='declencheurenum'), nullable=False),
    sa.Column('envoye_le', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_commande'], ['commandes.id_commande'], ),
    sa.PrimaryKeyConstraint('id_notification')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('commandes')
    op.drop_table('livreurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
