"""ajout table codes_otp et flags verification

Revision ID: f41e277fafbe
Revises: a821aa3693f5
Create Date: 2026-08-21 17:03:41.660439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f41e277fafbe'
down_revision: Union[str, Sequence[str], None] = 'a821aa3693f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes_otp',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('canal', sa.Enum('EMAIL', 'SMS', name='canalotp'), nullable=False),
    sa.Column('objectif', sa.Enum('VERIFICATION_INSCRIPTION', 'REINITIALISATION_MDP', name='objectifotp'), nullable=False),
    sa.Column('expire_le', sa.DateTime(), nullable=False),
    sa.Column('utilise', sa.Boolean(), nullable=False),
    sa.Column('tentatives', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('utilisateurs', sa.Column('telephone_verifie', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('utilisateurs', sa.Column('email_verifie', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'email_verifie')
    op.drop_column('utilisateurs', 'telephone_verifie')
    op.drop_table('codes_otp')
    # ### end Alembic commands ###
